FROM python:3.11-slim

# Instalar dependencias del sistema necesarias (como curl para el healthcheck)
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Puerto expuesto por Flask
EXPOSE 5001

CMD ["python", "app.py"]